function dJxw = dJxw_f(z6,z7)
%DJXW_F
%    DJXW = DJXW_F(Z6,Z7)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Aug-2019 10:00:13

t2 = cos(z6);
t3 = sin(z6);
t4 = t2.*z7.*(3.0./2.0e+2);
t5 = t3.*z7.*(3.0./2.0e+2);
t6 = -t5;
dJxw = reshape([t6,t4,1.0./5.0,0.0,0.0,0.0,0.0,t6,t4,-1.0./5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7,6]);
