function Jxw = Jxw_f(z6)
%JXW_F
%    JXW = JXW_F(Z6)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Aug-2019 12:08:41

t2 = cos(z6);
t3 = sin(z6);
t4 = t2.*(3.0./2.0e+2);
t5 = t3.*(3.0./2.0e+2);
Jxw = reshape([t4,t5,1.0./5.0,0.0,0.0,0.0,0.0,t4,t5,-1.0./5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7,6]);
