function Jk = Jk_f(z1)
%JK_F
%    JK = JK_F(Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Aug-2019 16:07:17

Jk = [sin(z1).*(-3.0./1.0e+1);cos(z1).*(3.0./1.0e+1);0.0];
