function Gk = Gk_f(z14,z16,z18)
%GK_F
%    GK = GK_F(Z14,Z16,Z18)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    03-Aug-2019 17:54:43

t2 = z14+z16;
t3 = cos(t2);
t4 = t2+z18;
t5 = cos(t4);
t8 = t3.*5.644674e-1;
t6 = t5.*1.962e-1;
t9 = -t8;
t7 = -t6;
Gk = [0.0;0.0;0.0;t7+t9-cos(z14-pi./2.0+4.9e+1./2.0e+2).*7.02588276e-1;t7+t9;t7];
