function dJk = dJk_f(z1,z2)
%DJK_F
%    DJK = DJK_F(Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Aug-2019 19:58:59

dJk = [z2.*cos(z1).*(-3.0./1.0e+1);z2.*sin(z1).*(-3.0./1.0e+1);0.0];
